import type { Plan, ActivityItem, AIInsight } from "@/types";

// ─── Plans ──────────────────────────────────────────────────────────────────

export const PLACEHOLDER_PLANS: Plan[] = [
  {
    id: "plan-1",
    heading: "Full-Stack Developer Job Prep",
    summary:
      "Structured weekly plan to land your next role: portfolio polish, LeetCode sprints, and interview simulations.",
    planType: "Weekly",
    productivityScore: 82,
    focusTime: "5h 30m",
    breakTime: "1h 15m",
    completionEstimate: "7 days",
    totalTasks: 12,
    days: [
      {
        day: "Monday",
        date: "2025-06-23",
        items: [
          {
            id: "t1",
            title: "Polish GitHub profile README",
            taskType: "Career",
            priority: "High",
            period: "Morning",
            time: "09:00",
            duration: "45m",
            completed: true,
            aiNote: "Recruiters check this first.",
          },
          {
            id: "t2",
            title: "Solve 3 LeetCode medium problems",
            taskType: "Coding",
            priority: "High",
            period: "Morning",
            time: "10:00",
            duration: "90m",
            completed: true,
            aiNote: "Focus on arrays and sliding window.",
          },
          {
            id: "t3",
            title: "Update portfolio with last project",
            taskType: "Career",
            priority: "Medium",
            period: "Afternoon",
            time: "14:00",
            duration: "60m",
            completed: false,
            aiNote: "Add live demo link.",
          },
          {
            id: "t4",
            title: "Cold-email 5 engineering managers",
            taskType: "Networking",
            priority: "Medium",
            period: "Evening",
            time: "18:00",
            duration: "40m",
            completed: false,
            aiNote: "Keep it under 120 words.",
          },
        ],
      },
      {
        day: "Tuesday",
        date: "2025-06-24",
        items: [
          {
            id: "t5",
            title: "System design study: Distributed caching",
            taskType: "Study",
            priority: "High",
            period: "Morning",
            time: "09:30",
            duration: "60m",
            completed: false,
            aiNote: "Redis and Memcached patterns.",
          },
          {
            id: "t6",
            title: "Mock interview with peer",
            taskType: "Interview Prep",
            priority: "High",
            period: "Afternoon",
            time: "15:00",
            duration: "90m",
            completed: false,
            aiNote: "Record for review.",
          },
          {
            id: "t7",
            title: "Write cover letter template",
            taskType: "Career",
            priority: "Low",
            period: "Evening",
            time: "19:00",
            duration: "30m",
            completed: false,
            aiNote: "One strong template beats ten weak ones.",
          },
        ],
      },
      {
        day: "Wednesday",
        date: "2025-06-25",
        items: [
          {
            id: "t8",
            title: "Review data structures flashcards",
            taskType: "Study",
            priority: "Medium",
            period: "Morning",
            time: "08:00",
            duration: "30m",
            completed: false,
            aiNote: "",
          },
          {
            id: "t9",
            title: "Deploy portfolio to Vercel",
            taskType: "Coding",
            priority: "High",
            period: "Morning",
            time: "10:00",
            duration: "45m",
            completed: false,
            aiNote: "Set custom domain too.",
          },
          {
            id: "t10",
            title: "LinkedIn post about recent project",
            taskType: "Networking",
            priority: "Low",
            period: "Evening",
            time: "18:30",
            duration: "20m",
            completed: false,
            aiNote: "Storytelling > bullet points.",
          },
          {
            id: "t11",
            title: "Research target companies",
            taskType: "Career",
            priority: "Medium",
            period: "Afternoon",
            time: "13:00",
            duration: "60m",
            completed: false,
            aiNote: "",
          },
          {
            id: "t12",
            title: "Watch system design masterclass",
            taskType: "Study",
            priority: "Medium",
            period: "Night",
            time: "21:00",
            duration: "90m",
            completed: false,
            aiNote: "",
          },
        ],
      },
    ],
  },
  {
    id: "plan-2",
    heading: "Morning Wellness & Focus Routine",
    summary:
      "Daily habit stack to boost cognitive clarity: movement, journaling, deep work blocks, and intentional rest.",
    planType: "Daily",
    productivityScore: 91,
    focusTime: "3h 00m",
    breakTime: "45m",
    completionEstimate: "Today",
    totalTasks: 7,
    days: [
      {
        day: "Today",
        date: "2025-06-27",
        items: [
          {
            id: "w1",
            title: "10-minute cold plunge or walk",
            taskType: "Wellness",
            priority: "High",
            period: "Morning",
            time: "06:30",
            duration: "10m",
            completed: true,
            aiNote: "Builds cortisol resilience.",
          },
          {
            id: "w2",
            title: "Gratitude journal — 3 entries",
            taskType: "Mindfulness",
            priority: "Medium",
            period: "Morning",
            time: "06:45",
            duration: "10m",
            completed: true,
            aiNote: "Short and honest beats long and vague.",
          },
          {
            id: "w3",
            title: "90-minute deep work block",
            taskType: "Focus",
            priority: "High",
            period: "Morning",
            time: "08:00",
            duration: "90m",
            completed: true,
            aiNote: "Phone in another room.",
          },
          {
            id: "w4",
            title: "25-min walk or stretching",
            taskType: "Wellness",
            priority: "Medium",
            period: "Afternoon",
            time: "12:30",
            duration: "25m",
            completed: false,
            aiNote: "Natural light resets focus.",
          },
          {
            id: "w5",
            title: "Read 20 pages",
            taskType: "Learning",
            priority: "Low",
            period: "Afternoon",
            time: "17:00",
            duration: "30m",
            completed: false,
            aiNote: "",
          },
          {
            id: "w6",
            title: "Evening wind-down — no screens",
            taskType: "Wellness",
            priority: "Medium",
            period: "Evening",
            time: "21:00",
            duration: "45m",
            completed: false,
            aiNote: "Dim lights 2h before bed.",
          },
          {
            id: "w7",
            title: "Reflect & plan tomorrow",
            taskType: "Planning",
            priority: "High",
            period: "Night",
            time: "21:45",
            duration: "15m",
            completed: false,
            aiNote: "5-minute brain dump clears mental RAM.",
          },
        ],
      },
    ],
  },
  {
    id: "plan-3",
    heading: "Launch Side Project MVP",
    summary:
      "Sprint plan to ship a working MVP of your SaaS idea: from wireframe to deployed, paying-user-ready product.",
    planType: "Monthly",
    productivityScore: 68,
    focusTime: "8h 00m",
    breakTime: "2h 00m",
    completionEstimate: "30 days",
    totalTasks: 10,
    days: [
      {
        day: "Week 1",
        date: "2025-06-23",
        items: [
          {
            id: "s1",
            title: "Finalize product scope & core features",
            taskType: "Planning",
            priority: "High",
            period: "Morning",
            time: "09:00",
            duration: "120m",
            completed: true,
            aiNote: "Scope creep kills MVPs.",
          },
          {
            id: "s2",
            title: "Design wireframes in Figma",
            taskType: "Design",
            priority: "High",
            period: "Morning",
            time: "11:00",
            duration: "180m",
            completed: true,
            aiNote: "3 screens max for MVP.",
          },
          {
            id: "s3",
            title: "Set up Next.js + Supabase project",
            taskType: "Coding",
            priority: "High",
            period: "Afternoon",
            time: "14:00",
            duration: "60m",
            completed: false,
            aiNote: "Use the starter template.",
          },
          {
            id: "s4",
            title: "Build auth flow",
            taskType: "Coding",
            priority: "High",
            period: "Afternoon",
            time: "15:30",
            duration: "120m",
            completed: false,
            aiNote: "Magic link is fastest to implement.",
          },
        ],
      },
      {
        day: "Week 2",
        date: "2025-06-30",
        items: [
          {
            id: "s5",
            title: "Build core feature #1",
            taskType: "Coding",
            priority: "High",
            period: "Morning",
            time: "09:00",
            duration: "240m",
            completed: false,
            aiNote: "",
          },
          {
            id: "s6",
            title: "Stripe payment integration",
            taskType: "Coding",
            priority: "High",
            period: "Afternoon",
            time: "14:00",
            duration: "120m",
            completed: false,
            aiNote: "Monthly + yearly pricing.",
          },
          {
            id: "s7",
            title: "Write landing page copy",
            taskType: "Marketing",
            priority: "Medium",
            period: "Evening",
            time: "18:00",
            duration: "60m",
            completed: false,
            aiNote: "Problem → Solution → CTA",
          },
        ],
      },
      {
        day: "Week 3",
        date: "2025-07-07",
        items: [
          {
            id: "s8",
            title: "Beta test with 5 users",
            taskType: "Research",
            priority: "High",
            period: "Afternoon",
            time: "14:00",
            duration: "180m",
            completed: false,
            aiNote: "",
          },
          {
            id: "s9",
            title: "Fix critical bugs from beta feedback",
            taskType: "Coding",
            priority: "High",
            period: "Morning",
            time: "09:00",
            duration: "120m",
            completed: false,
            aiNote: "",
          },
          {
            id: "s10",
            title: "Launch on Product Hunt",
            taskType: "Marketing",
            priority: "High",
            period: "Morning",
            time: "00:01",
            duration: "30m",
            completed: false,
            aiNote: "Tuesday or Wednesday mornings perform best.",
          },
        ],
      },
    ],
  },
];

// ─── Sidebar Data ────────────────────────────────────────────────────────────

export const ACTIVITY_ITEMS: ActivityItem[] = [
  {
    id: "a1",
    action: 'Plan "Full-Stack Developer Job Prep" generated',
    time: "2 hours ago",
    type: "plan_generated",
  },
  {
    id: "a2",
    action: 'Task "Solve LeetCode problems" completed',
    time: "3 hours ago",
    type: "task_completed",
  },
  {
    id: "a3",
    action: "Morning Wellness plan saved",
    time: "Yesterday, 9:14 AM",
    type: "plan_saved",
  },
  {
    id: "a4",
    action: 'Task "Deep work block" rescheduled',
    time: "Yesterday, 8:30 AM",
    type: "task_rescheduled",
  },
  {
    id: "a5",
    action: "Firebase sync — 3 plans updated",
    time: "2 days ago",
    type: "sync",
  },
];

export const AI_INSIGHTS: AIInsight[] = [
  {
    id: "i1",
    icon: "🧠",
    text: "You complete coding tasks 40% faster before noon. Schedule deep work in the morning.",
  },
  {
    id: "i2",
    icon: "📈",
    text: "Your productivity score is up 12 points this week — your best in a month.",
  },
  {
    id: "i3",
    icon: "🔥",
    text: "Current streak: 6 days. Keep going — your record is 11 days.",
  },
];
